version: 2

models:
  - name: stg_users
    description: User info
    columns:
      - name: user_guid
        description: Primary key for users
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: created_at_utc
      - name: updated_at_utc
      - name: address_guid

  - name: stg_addresses
    columns:
      - name: address_guid
        tests:
          - unique
          - not_null
      - name: address
      - name: zipcode
      - name: state
      - name: country

  - name: stg_events
    columns:
      - name: event_guid
        tests:
          - unique
          - not_null
      - name: session_guid
      - name: user_guid
      - name: event_type
      - name: page_url
      - name: created_at_utc

  - name: stg_orders
    columns:
      - name: order_guid
        tests:
          - unique
          - not_null
      - name: promo_guid
      - name: user_guid
      - name: address_guid
      - name: created_at_utc
      - name: order_cost_usd
      - name: shipping_cost_usd
      - name: order_total_usd
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at_utc
      - name: delivered_at_utc
      - name: status

  - name: stg_order_items
    columns:
      - name: order_guid
      - name: product_guid
      - name: quantity

  - name: stg_products
    columns:
      - name: product_guid
        tests:
          - unique
          - not_null
      - name: name
      - name: price_usd
        tests:
          - positive_values
      - name: inventory

  - name: stg_promos
    columns:
      - name: promo_id
        tests:
          - unique
          - not_null
      - name: discount_usd
        tests:
          - positive_values
      - name: status
