version: 2

models:
  - name: stg_users
    description: User info
    columns:
      - name: user_id
        description: Primary key for users
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: created_at
      - name: updated_at
      - name: address_id

  - name: stg_addresses
    columns:
      - name: address_id
        tests:
          - unique
          - not_null
      - name: address
      - name: zipcode
      - name: state
      - name: country

  - name: stg_events
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: session_id
      - name: user_id
      - name: event_type
      - name: page_url
      - name: created_at

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: promo_id
      - name: user_id
      - name: address_id
      - name: created_at
      - name: order_cost
      - name: shipping_cost
      - name: order_total
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status

  - name: stg_order_items
    columns:
      - name: order_id
      - name: product_id
      - name: quantity

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: name
      - name: price
        tests:
          - positive_values
      - name: inventory

  - name: stg_promos
    columns:
      - name: promo_id
        tests:
          - unique
          - not_null
      - name: discount
        tests:
          - positive_values
      - name: status
